sudo: false
language: ruby

install: 'gem install bundler; bundle install --retry=3'
before_script: unset CI
script: 'ruby --enable-frozen-string-literal -vr bundler/setup -S rake test'

matrix:
  include:
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: ruby-head
    - rvm: jruby
      env: JRUBY_OPTS=--debug
    - rvm: rbx

  allow_failures:
    - rvm: rbx
